window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.ko={
    meta:{htmlLang:'ko',title:'파파존스 모바일 키오스크 v43.9.3'},
    labels:{
      orderType:{takeout:'포장',dinein:'먹고가기'},
      promo:{normal:'일반주문',takeout:'포장 20%',happy:'해피아워',upup:'UP & UP',set:'세트메뉴'},
      dough:{original:'오리지널',thin:'씬도우',croissant:'크루아상'},
      crust:{original:'오리지널',cheeseRoll:'치즈롤',goldRing:'골드링',thin:'씬도우',croissant:'크루아상'},
      size:{R:'레귤러사이즈',L:'라지사이즈',F:'패밀리사이즈'},
      payment:{cash:'현금',card:'신용카드',meal_ticket:'식권대장',bizle:'비즐식권'}
    },
    home:{
      location:'파파존스 판교2테크노밸리점',headlinePrefix:'오늘도 ',headlineAccent:'갓 구운',headlineSuffix:' 피자를 즐겨보세요!',tagline:'Better Ingredients. Better Pizza.',
      dineInTitle:'먹고가기',dineInFeatureMeal:'편안한 매장 식사',dineInFeatureSeats:'다양한 좌석',dineInFeatureSet:'세트 메뉴 주문',
      takeoutTitle:'포장하기',takeoutFeatureFast:'빠르고 간편한 포장',takeoutFeatureReady:'바로 포장 가능',takeoutFeatureBenefit:'할인 혜택',
      happyHourDeal:'R 사이즈 피자 15,000원',takeoutDeal:'L/F 포장 20% 할인',takeoutDealDesc:'포장 할인으로 바로 주문',beerTitle:'피맥 가능!',beerHeineken:'하이네켄 생맥주 8,000원',beerBudweiser:'버드와이저 병맥주 5,000원'
    },
    orderType:{title:'어떻게 이용하시나요?'},
    benefit:{title:'주문 유형을 선택해 주세요',subtitle:{dinein:'세트메뉴, UP & UP, 일반주문 중 선택해 주세요.',takeout:'원하는 혜택을 선택해 주세요.'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UP은 L 사이즈 판매 피자 전용이며, L 피자 가격으로 결제하고 F 사이즈와 선택 크러스트로 무료 업그레이드됩니다.'},card:{set:{title:'세트메뉴',desc:'2인 · 3인 · 4인',pill:'인원에 맞춘 알찬 구성'},upup:{title:'UP & UP',desc:'라지 주문 시 패밀리 업그레이드',pill:'크러스트까지 무료'},normal:{title:'일반주문',desc:'원하는 메뉴와 옵션 선택',pill:'자유롭게 주문'},happy:{title:'해피아워',desc:'16:00~20:00 R 사이즈',pill:'15,000원'},takeout:{title:'포장 20%',desc:'L/F 피자 포장',pill:'20% 할인'}},setChoice:{title:'세트메뉴를 선택해 주세요',subtitle:'인원에 맞는 구성을 확인한 뒤 세트를 선택해 주세요.',select:'선택하기 →',note:'세트메뉴는 오리지널 도우로 제공되며, 세트에 따라 사이즈가 자동 적용됩니다. 하프앤하프 선택 시 세트 금액에 1,000원만 추가됩니다.',item:{pizza:'피자',pasta:'파스타',cola:'콜라',sideOne:'사이드 1종',chicken:'치킨'},card:{two:{badge:'2인 추천',title:'2인 세트',size:'레귤러 전용',desc:'피자 + 파스타 + 작은 음료'},three:{badge:'3인 추천',title:'3인 세트',size:'라지 전용',desc:'피자 + 사이드 1종 + 큰 음료'},four:{badge:'가장 인기',title:'4인 세트',size:'패밀리 전용',desc:'피자 + 사이드 2종 + 큰 음료'}}}},
    dough:{optionSetupTitle:'포장 피자 옵션 선택',optionSetupSubtitle:'한판 구성과 사이즈·도우·크러스트를 한 화면에서 선택하세요.',compositionTitle:'1. 피자 구성',optionSection:'3. 도우 타입',choosePizza:'피자 선택하기 →',item:{original:{name:'오리지널',desc:'기본 도우의 쫄깃하고 담백한 맛'},thin:{name:'씬도우',desc:'얇고 바삭한 식감의 도우'},croissant:{name:'크루아상',desc:'버터 풍미와 겹겹이 바삭한 도우'}}},
    size:{optionSection:'2. 사이즈',title:'사이즈 선택',subtitle:'피자 지름과 권장 인원을 확인한 뒤 선택해 주세요.',note:'※ 권장 인원은 식사량과 함께 주문하는 메뉴에 따라 달라질 수 있습니다.',takeoutUnavailable:'포장 할인 불가',takeoutDiscount:'20% 할인',halfUnavailable:'레귤러 사이즈는 하프앤하프 선택 불가',item:{R:{name:'레귤러',inch:'9인치',desc:'1~2인용'},L:{name:'라지',inch:'12인치',desc:'2~3인용'},F:{name:'패밀리',inch:'14인치',desc:'3~4인용'}}},
    crust:{optionSection:'4. 크러스트 타입',setTitle:'{count}인 세트 피자 구성',summary:'선택 요약',modeSection:'1. 한판 / 하프앤하프 선택',selectSection:'2. 크러스트 선택',title:'크러스트를 선택해 주세요',subtitle:'이미지 없이 이름·설명·추가금만 간결하게 표시합니다.',noExtraFee:'추가금 없음',free:'무료',upupCroissantNotice:'UP&UP 선택 시 라지 사이즈로 제공',item:{original:{name:'오리지널',desc:'기본 도우의 쫄깃하고 담백한 맛'},thin:{name:'씬',desc:'바삭하고 담백한 얇은 씬 크러스트',sizeLabel:'F 전용'},cheeseRoll:{name:'치즈롤',desc:'호불호 없는 부드러운 치즈 크러스트'},goldRing:{name:'골드링',desc:'달콤한 고구마와 치즈가 어우러진 크러스트'},croissant:{name:'크루아상',desc:'겹겹이 살아있는 바삭함과 버터 풍미',sizeLabel:'L 전용'}}},
    pizza:{title:{single:'피자 선택',first:'첫 번째 피자 선택',second:'두 번째 피자 선택'},secondPizzaPlaceholder:'두 번째 피자 선택',changeOptions:'옵션 변경',halfUnavailable:'선택한 피자와 하프앤하프 불가',category:{ALL:'전체',BEST:'BEST',SPECIALTY:'스페셜티',CLASSIC:'클래식',THIN:'씬'},mode:{single:'한판',half:'하프앤하프'},price:{normal:'정상금액',discount:'할인금액',final:'할인 후'},item:{P001:{name:'수퍼 파파스',desc:'신선한 토마토 소스 위에 각종 고기와 채소가 듬뿍 토핑된 파파존스의 베스트 피자'},P002:{name:'존스 페이버릿',desc:'이탈리안 소시지, 페퍼로니와 6종의 치즈가 만들어 내는 진한 풍미의 베스트 셀러'},P003:{name:'올미트',desc:'페퍼로니, 햄, 이탈리안 소시지, 비프토핑까지 엄선된 고기토핑으로 꽉 채운 피자'},P004:{name:'스파이시 치킨랜치',desc:'랜치 소스, 그릴드 치킨, 토마토와 할라페뇨가 토핑된 피자'},P005:{name:'아이리쉬 포테이토',desc:'진한 갈릭 소스와 담백한 포테이토 청크의 조화'},P006:{name:'치킨 바베큐',desc:'새콤달콤한 페퍼 BBQ 소스와 두툼한 그릴드 치킨의 조화'},P007:{name:'햄 머쉬룸 식스 치즈',desc:'알프레도 소스, 양송이 버섯, 햄과 6가지 치즈의 조화'},P008:{name:'프리미엄 직화불고기',desc:'정통 직화 불고기와 신선한 채소 토핑'},P009:{name:'식스 치즈',desc:'6종 치즈가 어우러진 진한 치즈 피자'},P010:{name:'스파이시 이탈리안',desc:'이탈리안 소시지와 크러쉬드 레드페퍼의 매운맛'},P011:{name:'THIN 슈림프 알프레도',desc:'얇고 바삭한 씬도우 위에 알프레도 소스와 새우가 올라간 피자'},P012:{name:'마가리타',desc:'진한 토마토 소스와 모짜렐라 치즈가 토핑된 치즈피자'},P013:{name:'페퍼로니',desc:'페퍼로니와 치즈가 토핑된 피자'},P014:{name:'하와이안',desc:'파인애플과 햄, 모짜렐라 치즈 토핑'},P015:{name:'가든 스페셜',desc:'양송이, 청피망, 올리브, 양파, 토마토 등 채소가 토핑된 피자'}}},
    pickup:{title:'포장 주문 시간을 선택해 주세요',subtitle:'바로 주문하거나 오늘 픽업할 시간을 예약할 수 있습니다.',now:'바로 주문',nowDesc:'지금 주문하고 준비되는 대로 픽업합니다.',reserve:'예약 주문',reserveDesc:'오늘 원하는 픽업 시간을 선택합니다.',closed:'오늘 예약 가능한 시간이 마감되었습니다.',reserveTitle:'픽업 예약 시간을 선택해 주세요',reserveGuide:'현재 시각에서 최소 30분 이후부터 10분 단위로 예약할 수 있습니다.',hour:'시간',minute:'분',hourUnit:'시',minuteUnit:'분',selectedTime:'선택 시간',confirm:'예약 시간 확정',noAvailableTime:'오늘 예약 가능한 시간이 없습니다.',chooseNow:'바로 주문을 선택해 주세요.',changeTime:'주문 시간 다시 선택'},
    party:{title:'이용 인원을 선택해 주세요',guide:'− 또는 + 버튼으로 인원을 조정한 뒤 다음으로 이동하세요.',count:'{count}{unit}',personUnit:'명',range:'최소 1명 · 최대 16명',roomAvailable:'ROOM을 선택할 수 있습니다.',roomMinimum:'룸은 최초 6명 이상부터 선택할 수 있습니다.',outdoorOnly:'13~16명은 야외존만 선택할 수 있습니다.',areaGuide:'인원수와 현재 빈자리에 맞춰 이용 가능한 구역이 표시됩니다.',next:'다음 →',decrease:'인원 줄이기',increase:'인원 늘리기'},
    seat:{areaTitle:'식사 구역을 선택해 주세요',areaGuide:'모든 구역을 표시합니다. 현재 이용할 수 없는 구역은 회색으로 표시되며, 누르면 이용 사유를 확인할 수 있습니다.',fullWaitlist:'만석 · 줄서기 가능',availableSeats:'{count}석 이용 가능',currentUnavailable:'현재 선택 불가',policyTitle:'좌석 운영 안내',policyGuide:'파파존·야외존: 매일 11:00~21:00 (라스트오더 20:30)<br>보틀존·보틀룸존: 평일 11:00~14:00 / 토요일 15:00~21:00 주류 이용 시 가능 (라스트오더 20:30) / 일요일 휴무',occupancyNote:'만석 구역을 선택하면 사용 중인 테이블에서 줄서기를 등록할 수 있습니다.',selectSeat:'{area} 자리 선택',seatGuide:'{count}개의 테이블을 선택해 주세요. 선택한 구역 안에서만 좌석을 고를 수 있습니다.',queueCount:'대기 {count}팀',queueButton:'이 좌석 줄서기',summaryReady:'✓ 좌석 선택 완료',summaryPrompt:'좌석을 선택해 주세요',summaryDetail:'선택 테이블 {selected} / {needed} · 총 {seats}석',personSeat:'{count}인석',selectedName:'{name} 선택됨',area:{papaZone:'파파존',annex:'보틀존',privateRoom:'보틀룸존',outdoor:'야외존'},status:{available:'이용 가능',selected:'선택됨',occupied:'사용 중',unavailable:'이용 불가'},type:{twoPerson:'커플석',barTable:'4인 바테이블',room:'ROOM',outdoorTable:'야외 테이블'},hours:{daily:'매일 11:00~21:00 · 라스트오더 20:30',limited:'평일 11:00~14:00 · 토요일 15:00~21:00(주류 이용 시) · 일요일 휴무'},reason:{beforeOpenDaily:'현재 이용 전입니다. 오전 11시부터 이용 가능합니다.',lastOrderClosed:'라스트오더가 마감되었습니다. (20:30)',closedToday:'오늘 좌석 이용이 종료되었습니다.',availableNow:'현재 이용 가능합니다.',sundayClosed:'일요일은 운영하지 않습니다.',weekdayBeforeOpen:'평일은 오전 11시부터 이용 가능합니다.',weekdayClosed:'평일 좌석 이용은 14:00에 종료됩니다.',weekdayAvailable:'평일 11:00~14:00 이용 가능합니다.',saturdayBeforeOpen:'토요일은 15:00부터 주류 주문 고객만 이용 가능합니다.',alcoholOnly:'주류 주문 고객만 이용 가능합니다.',genericUnavailable:'현재 이용할 수 없습니다.',partyUnavailable:'{count}명 이용 규정상 선택할 수 없는 구역입니다.'},rule:{twoOrLess:'파파존 커플석·바테이블, 보틀존 1번·4번, 야외존에서 {count}개를 선택할 수 있습니다.',fourOrLess:'파파존 바테이블, 보틀존 2번·3번, 야외존에서 {count}개를 선택할 수 있습니다.',five:'보틀존 2번·3번 또는 야외존에서 {count}개를 선택할 수 있습니다.',roomOrOutdoor:'보틀룸존 또는 야외존에서 {count}개를 선택할 수 있습니다.',outdoorOnly:'13~16명은 야외존에서 {count}개를 선택해야 합니다.'},desc:{coupleBar:'커플석 · 바테이블',barTable:'바테이블',annexSmall:'1번 · 4번',annexMedium:'2번 · 3번',unavailable:'이용 불가',roomTables:'4인 테이블 {count}개 선택',outdoorTables:'4인 테이블 {count}개 선택'}},
    nav:{home:'처음으로',previous:'이전',next:'다음'},
    phone:{title:'전화번호를 입력해 주세요',subtitle:'010은 고정입니다. 뒤 8자리를 모두 입력해 주세요.',clear:'전체삭제',orderNumber:'주문번호(전화번호 뒤 4자리):',invalid:'전화번호 뒤 8자리를 정확히 입력해 주세요.',next:'결제수단 선택'},
    done:{title:'주문이 접수되었습니다',orderLabel:'주문번호 · 전화번호 뒤 4자리',paymentRequired:'{payment}로 카운터에서 결제해 주세요',paymentGuide:'결제 완료 후 피자 제조가 시작됩니다.',reserveTime:'예약시간 {time}',guide:'주문번호를 확인하시고 카운터로 와 주세요.',home:'처음으로'}
  };
