window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.zh={
    meta:{htmlLang:'zh',title:'Papa John\'s 移动自助点餐 v43.9.3'},
    labels:{orderType:{takeout:'外带',dinein:'堂食'},promo:{normal:'普通点餐',takeout:'外带20%',happy:'HAPPY HOUR',upup:'UP & UP',set:'套餐'},dough:{original:'原味饼底',thin:'薄脆饼底',croissant:'可颂饼边'},crust:{original:'原味',cheeseRoll:'芝士卷边',goldRing:'金薯芝士圈',thin:'薄脆饼底',croissant:'可颂饼边'},size:{R:'普通尺寸',L:'大尺寸',F:'家庭尺寸'},payment:{cash:'现金',card:'信用卡',meal_ticket:'餐券大将',bizle:'Bizle餐券'}},
    home:{location:'Papa John\'s 板桥第二科技谷店',headlinePrefix:'今天也来享用',headlineAccent:'新鲜现烤',headlineSuffix:'披萨吧！',tagline:'Better Ingredients. Better Pizza.',dineInTitle:'堂食',dineInFeatureMeal:'舒适店内用餐',dineInFeatureSeats:'多种座位',dineInFeatureSet:'套餐点餐',takeoutTitle:'外带',takeoutFeatureFast:'快速便捷外带',takeoutFeatureReady:'可快速取餐',takeoutFeatureBenefit:'优惠折扣',happyHourDeal:'R尺寸披萨 15,000韩元',takeoutDeal:'L/F 外带8折',takeoutDealDesc:'使用外带折扣立即点餐',beerTitle:'可享披萨配啤酒！',beerHeineken:'Heineken 生啤 8,000韩元',beerBudweiser:'Budweiser 瓶装啤酒 5,000韩元'},
    orderType:{title:'请选择用餐方式'},
    benefit:{title:'请选择点餐类型',subtitle:{dinein:'请选择套餐、UP & UP或普通点餐。',takeout:'请选择想使用的优惠。'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UP仅适用于销售L尺寸的披萨。按L尺寸价格结算，可免费升级为F尺寸和所选饼边。'},card:{set:{title:'套餐',desc:'2人 · 3人 · 4人',pill:'按人数搭配的丰富组合'},upup:{title:'UP & UP',desc:'点Large升级为Family',pill:'饼边也免费'},normal:{title:'普通点餐',desc:'选择想要的菜单和选项',pill:'自由点餐'},happy:{title:'HAPPY HOUR',desc:'16:00–20:00 R尺寸',pill:'15,000韩元'},takeout:{title:'外带20%',desc:'L/F披萨外带',pill:'8折'}},setChoice:{title:'请选择套餐',subtitle:'确认适合人数的组合后选择套餐。',select:'选择 →',note:'套餐使用原味饼底，并根据套餐自动应用尺寸。选择Half & Half时仅在套餐金额上加1,000韩元。',item:{pizza:'披萨',pasta:'意面',cola:'可乐',sideOne:'1份小食',chicken:'鸡肉'},card:{two:{badge:'2人推荐',title:'2人套餐',size:'仅限Regular',desc:'披萨 + 意面 + 小饮料'},three:{badge:'3人推荐',title:'3人套餐',size:'仅限Large',desc:'披萨 + 1份小食 + 大饮料'},four:{badge:'最受欢迎',title:'4人套餐',size:'仅限Family',desc:'披萨 + 2份小食 + 大饮料'}}}},
    pickup:{title:'请选择外带取餐时间',subtitle:'可以立即点餐，或预约今天的取餐时间。',now:'立即点餐',nowDesc:'现在下单，制作完成后取餐。',reserve:'预约点餐',reserveDesc:'选择今天想要的取餐时间。',closed:'今天可预约时间已结束。',reserveTitle:'请选择预约取餐时间',reserveGuide:'可从当前时间至少30分钟后开始，以10分钟为单位预约。',hour:'小时',minute:'分钟',hourUnit:'点',minuteUnit:'分',selectedTime:'已选时间',confirm:'确认预约时间',noAvailableTime:'今天没有可预约时间。',chooseNow:'请选择立即点餐。',changeTime:'重新选择点餐时间'},
    party:{title:'请选择用餐人数',guide:'请用 − 或 + 调整人数后继续。',count:'{count}{unit}',personUnit:'人',range:'最少1人 · 最多16人',roomAvailable:'可以选择ROOM。',roomMinimum:'包间需6人以上才可选择。',outdoorOnly:'13–16人只能选择户外区。',areaGuide:'会根据人数和当前空位显示可用区域。',next:'下一步 →',decrease:'减少人数',increase:'增加人数'},
    seat:{areaTitle:'请选择用餐区域',areaGuide:'显示所有区域。当前不可用的区域会显示为灰色，点击可查看原因。',fullWaitlist:'满座 · 可排队',availableSeats:'可用{count}个座位',currentUnavailable:'当前不可选择',policyTitle:'座位使用指南',policyGuide:'Papa Zone·户外区：每天 11:00–21:00（最后点单20:30）<br>PapaBottle·ROOM：平日11:00–14:00 / 周六15:00–21:00 点酒时可用（最后点单20:30）/ 周日休息',occupancyNote:'满座区域可在使用中的桌位登记排队。',selectSeat:'选择{area}座位',seatGuide:'请选择{count}张桌子。只能在所选区域内选择座位。',queueCount:'等待 {count}组',queueButton:'此座位排队',summaryReady:'✓ 座位选择完成',summaryPrompt:'请选择座位',summaryDetail:'已选桌位 {selected} / {needed} · 共 {seats}个座位',personSeat:'{count}人座',selectedName:'已选择{name}',area:{papaZone:'Papa Zone',annex:'PapaBottle',privateRoom:'ROOM',outdoor:'户外区'},status:{available:'可用',selected:'已选择',occupied:'使用中',unavailable:'不可用'},type:{twoPerson:'双人座',barTable:'四人吧台桌',room:'ROOM',outdoorTable:'户外桌'},hours:{daily:'每天 11:00–21:00 · 最后点单 20:30',limited:'工作日 11:00–14:00 · 周六 15:00–21:00（点酒时） · 周日休息'},reason:{beforeOpenDaily:'尚未开放。上午11点起可使用。',lastOrderClosed:'最后点单已结束。（20:30）',closedToday:'今天座位使用已结束。',availableNow:'现在可以使用。',sundayClosed:'周日不营业。',weekdayBeforeOpen:'工作日上午11点起可使用。',weekdayClosed:'工作日座位使用于14:00结束。',weekdayAvailable:'工作日 11:00–14:00 可使用。',saturdayBeforeOpen:'周六15:00起仅限点酒顾客使用。',alcoholOnly:'仅限点酒顾客使用。',genericUnavailable:'当前不可使用。',partyUnavailable:'按{count}人使用规则，无法选择该区域。'},rule:{twoOrLess:'可在Papa Zone情侣座/吧台、PapaBottle 1号/4号或户外区选择{count}张桌。',fourOrLess:'可在Papa Zone吧台、PapaBottle 2号/3号或户外区选择{count}张桌。',five:'可在PapaBottle 2号/3号或户外区选择{count}张桌。',roomOrOutdoor:'可在ROOM或户外区选择{count}张桌。',outdoorOnly:'13–16人需在户外区选择{count}张桌。'},desc:{coupleBar:'情侣座 · 吧台',barTable:'吧台',annexSmall:'1号 · 4号',annexMedium:'2号 · 3号',unavailable:'不可使用',roomTables:'选择{count}张4人桌',outdoorTables:'选择{count}张4人桌'}},
    nav:{home:'返回首页',previous:'上一步',next:'下一步'},
    phone:{title:'请输入手机号码',subtitle:'010为固定号码。请输入后8位。',clear:'全部清除',orderNumber:'订单号（手机号后4位）:',invalid:'请正确输入手机号后8位。',next:'选择支付方式'},
    done:{title:'订单已接收',orderLabel:'订单号 · 手机号后4位',paymentRequired:'请在柜台使用{payment}支付',paymentGuide:'支付完成后将开始制作披萨。',reserveTime:'预约时间 {time}',guide:'请确认订单号后前往柜台。',home:'返回首页'}
  };
