window.PJ_I18N_LOCALES=window.PJ_I18N_LOCALES||{};
window.PJ_I18N_LOCALES.zh={
    meta:{htmlLang:'zh',title:'Papa John\'s 移动自助点餐 v43.9.3'},
    labels:{orderType:{takeout:'外带',dinein:'堂食'},promo:{normal:'普通点餐',takeout:'外带20%',happy:'HAPPY HOUR',upup:'UP & UP',set:'套餐'},dough:{original:'原味饼底',thin:'薄脆饼底',croissant:'可颂饼边'},crust:{original:'原味',cheeseRoll:'芝士卷边',goldRing:'金薯芝士圈',thin:'薄脆饼底',croissant:'可颂饼边'},size:{R:'普通尺寸',L:'大尺寸',F:'家庭尺寸'},payment:{cash:'现金',card:'信用卡',meal_ticket:'餐券大将',bizle:'Bizle餐券'}},
    home:{location:'Papa John\'s 板桥第二科技谷店',headlinePrefix:'今天也来享用',headlineAccent:'新鲜现烤',headlineSuffix:'披萨吧！',tagline:'Better Ingredients. Better Pizza.',dineInTitle:'堂食',dineInFeatureMeal:'舒适店内用餐',dineInFeatureSeats:'多种座位',dineInFeatureSet:'套餐点餐',takeoutTitle:'外带',takeoutFeatureFast:'快速便捷外带',takeoutFeatureReady:'可快速取餐',takeoutFeatureBenefit:'优惠折扣',happyHourDeal:'R尺寸披萨 15,000韩元',takeoutDeal:'L/F 外带8折',takeoutDealDesc:'使用外带折扣立即点餐',beerTitle:'可享披萨配啤酒！',beerHeineken:'Heineken 生啤 8,000韩元',beerBudweiser:'Budweiser 瓶装啤酒 5,000韩元'},
    orderType:{title:'请选择用餐方式'},
    benefit:{title:'请选择点餐类型',subtitle:{dinein:'请选择套餐、UP & UP或普通点餐。',takeout:'请选择想使用的优惠。'},bestChoice:'BEST CHOICE',best:'BEST',note:{upup:'UP & UP仅适用于销售L尺寸的披萨。按L尺寸价格结算，可免费升级为F尺寸和所选饼边。'},card:{set:{title:'套餐',desc:'2人 · 3人 · 4人',pill:'按人数搭配的丰富组合'},upup:{title:'UP & UP',desc:'点Large升级为Family',pill:'饼边也免费'},normal:{title:'普通点餐',desc:'选择想要的菜单和选项',pill:'自由点餐'},happy:{title:'HAPPY HOUR',desc:'16:00–20:00 R尺寸',pill:'15,000韩元'},takeout:{title:'外带20%',desc:'L/F披萨外带',pill:'8折'}},setChoice:{title:'请选择套餐',subtitle:'确认适合人数的组合后选择套餐。',select:'选择 →',note:'套餐使用原味饼底，并根据套餐自动应用尺寸。选择Half & Half时仅在套餐金额上加1,000韩元。',item:{pizza:'披萨',pasta:'意面',cola:'可乐',sideOne:'1份小食',chicken:'鸡肉'},card:{two:{badge:'2人推荐',title:'2人套餐',size:'仅限Regular',desc:'披萨 + 意面 + 小饮料'},three:{badge:'3人推荐',title:'3人套餐',size:'仅限Large',desc:'披萨 + 1份小食 + 大饮料'},four:{badge:'最受欢迎',title:'4人套餐',size:'仅限Family',desc:'披萨 + 2份小食 + 大饮料'}}}},
    dough:{optionSetupTitle:'选择外带披萨选项',optionSetupSubtitle:'在一个页面选择整张/拼半、尺寸、饼底和饼边。',compositionTitle:'1. 披萨组合',optionSection:'3. 饼底类型',choosePizza:'选择披萨 →',item:{original:{name:'原味饼底',desc:'经典饼底的筋道清爽口感'},thin:{name:'薄脆饼底',desc:'轻薄酥脆口感的饼底'},croissant:{name:'可颂饼底',desc:'带有黄油香气和层层酥脆感的饼底'}}},
    size:{optionSection:'2. 尺寸',title:'选择尺寸',subtitle:'请确认披萨直径和建议人数后选择。',note:'※ 建议人数会因食量和一起点的菜单而不同。',takeoutUnavailable:'不可享外带折扣',takeoutDiscount:'8折',halfUnavailable:'Regular尺寸不可选择Half & Half',item:{R:{name:'Regular',inch:'9英寸',desc:'1–2人用'},L:{name:'Large',inch:'12英寸',desc:'2–3人用'},F:{name:'Family',inch:'14英寸',desc:'3–4人用'}}},
    crust:{optionSection:'4. 饼边类型',setTitle:'{count}人套餐披萨组合',summary:'选择摘要',modeSection:'1. 整张 / Half & Half选择',selectSection:'2. 选择饼边',title:'请选择饼边',subtitle:'不显示图片，仅简洁显示名称、说明和加价。',noExtraFee:'无加价',free:'免费',upupCroissantNotice:'选择UP&UP时将以Large尺寸提供',item:{original:{name:'原味',desc:'经典饼底的筋道清爽口感'},thin:{name:'薄脆',desc:'轻薄酥脆的饼边',sizeLabel:'仅F'},cheeseRoll:{name:'芝士卷边',desc:'柔软顺口的芝士饼边'},goldRing:{name:'金薯芝士圈',desc:'甜薯与芝士融合的饼边'},croissant:{name:'可颂',desc:'层层酥脆并带有黄油香气',sizeLabel:'仅L'}}},
    pizza:{title:{single:'选择披萨',first:'选择第一款披萨',second:'选择第二款披萨'},secondPizzaPlaceholder:'选择第二款披萨',changeOptions:'更改选项',halfUnavailable:'所选披萨不可搭配Half & Half',category:{ALL:'全部',BEST:'BEST',SPECIALTY:'特色',CLASSIC:'经典',THIN:'薄脆'},mode:{single:'整张',half:'Half & Half'},price:{normal:'原价',discount:'优惠金额',final:'优惠后'},item:{P001:{name:'超级帕帕斯',desc:'在新鲜番茄酱上铺满多种肉类和蔬菜的Papa John’s经典披萨'},P002:{name:'约翰最爱',desc:'意式香肠、意式辣香肠和六种芝士带来浓郁风味的畅销款'},P003:{name:'全肉披萨',desc:'铺满意式辣香肠、火腿、意式香肠和牛肉粒等精选肉类'},P004:{name:'香辣鸡肉牧场',desc:'搭配牧场酱、烤鸡、番茄和墨西哥辣椒的披萨'},P005:{name:'爱尔兰土豆',desc:'浓郁蒜香酱与绵密土豆块的美味组合'},P006:{name:'鸡肉BBQ',desc:'酸甜胡椒BBQ酱搭配厚切烤鸡'},P007:{name:'火腿蘑菇六芝士',desc:'阿尔弗雷多酱、蘑菇、火腿与六种芝士的组合'},P008:{name:'高级直火烤肉',desc:'正宗直火烤牛肉搭配新鲜蔬菜配料'},P009:{name:'六芝士',desc:'六种芝士融合的浓郁芝士披萨'},P010:{name:'香辣意式',desc:'意式香肠与碎红椒带来的香辣风味'},P011:{name:'THIN 鲜虾阿尔弗雷多',desc:'薄脆饼底上搭配阿尔弗雷多酱和鲜虾'},P012:{name:'玛格丽塔',desc:'浓郁番茄酱与马苏里拉芝士的芝士披萨'},P013:{name:'意式辣香肠',desc:'铺有意式辣香肠和芝士的披萨'},P014:{name:'夏威夷',desc:'菠萝、火腿和马苏里拉芝士配料'},P015:{name:'田园特选',desc:'搭配蘑菇、青椒、橄榄、洋葱、番茄等蔬菜的披萨'}}},
    topping:{promptTitle:'要添加配料吗？',next:'下一步',skipDesc:'不加配料，继续选择小食',addTitle:'添加配料',limitGuide:'同种最多2份，总共最多5份',title:'选择配料',notice:'同种最多2份，总共最多5份。当前 {count}/5份',finishDesc:'按已选配料继续',selectedCount:'已选{count}份',free:'免费',limitTitle:'追加配料说明',limitEach:'同一种配料最多可添加<b>2份</b>。',limitTotal:'每张披萨最多可选择<b>5份</b>追加配料。<br>每种配料最多2份。',confirm:'确认',category:{cheese:'芝士',meat:'肉类',vegetable:'蔬菜'},item:{T001:{name:'2 Blend芝士',desc:'添加两种芝士，提升风味'},T002:{name:'3 Blend芝士',desc:'添加三种芝士，味道更浓郁'},T003:{name:'额外芝士',desc:'增加更多芝士'},T004:{name:'切达芝士',desc:'添加香浓切达芝士'},T005:{name:'意式香肠',desc:'风味浓郁的意式香肠'},T006:{name:'牛肉',desc:'清爽牛肉配料'},T007:{name:'培根',desc:'咸香培根'},T008:{name:'火腿',desc:'柔软火腿配料'},T009:{name:'意式辣香肠',desc:'微辣咸香的意式辣香肠'},T010:{name:'烤鸡',desc:'清爽烤鸡'},T011:{name:'洋葱',desc:'爽脆洋葱'},T012:{name:'青椒',desc:'清香青椒'},T013:{name:'番茄',desc:'新鲜番茄'},T014:{name:'玉米',desc:'香甜玉米'},T015:{name:'墨西哥辣椒',desc:'香辣墨西哥辣椒'},T016:{name:'黑橄榄',desc:'咸香黑橄榄'},T017:{name:'土豆',desc:'清淡土豆'},T018:{name:'菠萝',desc:'清爽菠萝'}}},
    pickup:{title:'请选择外带取餐时间',subtitle:'可以立即点餐，或预约今天的取餐时间。',now:'立即点餐',nowDesc:'现在下单，制作完成后取餐。',reserve:'预约点餐',reserveDesc:'选择今天想要的取餐时间。',closed:'今天可预约时间已结束。',reserveTitle:'请选择预约取餐时间',reserveGuide:'可从当前时间至少30分钟后开始，以10分钟为单位预约。',hour:'小时',minute:'分钟',hourUnit:'点',minuteUnit:'分',selectedTime:'已选时间',confirm:'确认预约时间',noAvailableTime:'今天没有可预约时间。',chooseNow:'请选择立即点餐。',changeTime:'重新选择点餐时间'},
    party:{title:'请选择用餐人数',guide:'请用 − 或 + 调整人数后继续。',count:'{count}{unit}',personUnit:'人',range:'最少1人 · 最多16人',roomAvailable:'可以选择ROOM。',roomMinimum:'包间需6人以上才可选择。',outdoorOnly:'13–16人只能选择户外区。',areaGuide:'会根据人数和当前空位显示可用区域。',next:'下一步 →',decrease:'减少人数',increase:'增加人数'},
    seat:{areaTitle:'请选择用餐区域',areaGuide:'显示所有区域。当前不可用的区域会显示为灰色，点击可查看原因。',fullWaitlist:'满座 · 可排队',availableSeats:'可用{count}个座位',currentUnavailable:'当前不可选择',policyTitle:'座位使用指南',policyGuide:'Papa Zone·户外区：每天 11:00–21:00（最后点单20:30）<br>PapaBottle·ROOM：平日11:00–14:00 / 周六15:00–21:00 点酒时可用（最后点单20:30）/ 周日休息',occupancyNote:'满座区域可在使用中的桌位登记排队。',selectSeat:'选择{area}座位',seatGuide:'请选择{count}张桌子。只能在所选区域内选择座位。',queueCount:'等待 {count}组',queueButton:'此座位排队',summaryReady:'✓ 座位选择完成',summaryPrompt:'请选择座位',summaryDetail:'已选桌位 {selected} / {needed} · 共 {seats}个座位',personSeat:'{count}人座',selectedName:'已选择{name}',area:{papaZone:'Papa Zone',annex:'PapaBottle',privateRoom:'ROOM',outdoor:'户外区'},status:{available:'可用',selected:'已选择',occupied:'使用中',unavailable:'不可用'},type:{twoPerson:'双人座',barTable:'四人吧台桌',room:'ROOM',outdoorTable:'户外桌'},hours:{daily:'每天 11:00–21:00 · 最后点单 20:30',limited:'工作日 11:00–14:00 · 周六 15:00–21:00（点酒时） · 周日休息'},reason:{beforeOpenDaily:'尚未开放。上午11点起可使用。',lastOrderClosed:'最后点单已结束。（20:30）',closedToday:'今天座位使用已结束。',availableNow:'现在可以使用。',sundayClosed:'周日不营业。',weekdayBeforeOpen:'工作日上午11点起可使用。',weekdayClosed:'工作日座位使用于14:00结束。',weekdayAvailable:'工作日 11:00–14:00 可使用。',saturdayBeforeOpen:'周六15:00起仅限点酒顾客使用。',alcoholOnly:'仅限点酒顾客使用。',genericUnavailable:'当前不可使用。',partyUnavailable:'按{count}人使用规则，无法选择该区域。'},rule:{twoOrLess:'可在Papa Zone情侣座/吧台、PapaBottle 1号/4号或户外区选择{count}张桌。',fourOrLess:'可在Papa Zone吧台、PapaBottle 2号/3号或户外区选择{count}张桌。',five:'可在PapaBottle 2号/3号或户外区选择{count}张桌。',roomOrOutdoor:'可在ROOM或户外区选择{count}张桌。',outdoorOnly:'13–16人需在户外区选择{count}张桌。'},desc:{coupleBar:'情侣座 · 吧台',barTable:'吧台',annexSmall:'1号 · 4号',annexMedium:'2号 · 3号',unavailable:'不可使用',roomTables:'选择{count}张4人桌',outdoorTables:'选择{count}张4人桌'}},
    nav:{home:'返回首页',previous:'上一步',next:'下一步'},
    phone:{title:'请输入手机号码',subtitle:'010为固定号码。请输入后8位。',clear:'全部清除',orderNumber:'订单号（手机号后4位）:',invalid:'请正确输入手机号后8位。',next:'选择支付方式'},
    done:{title:'订单已接收',orderLabel:'订单号 · 手机号后4位',paymentRequired:'请在柜台使用{payment}支付',paymentGuide:'支付完成后将开始制作披萨。',reserveTime:'预约时间 {time}',guide:'请确认订单号后前往柜台。',home:'返回首页'}
  };
